### ISSUE TITLE
Где нормальный project-layout?

### ISSUE THREAD

**Issue by midaef** [zvrvdmtr/advertising#1]
Привет, советую посмотреть разные репозитории и понять тебе как строить нормальный проект лайаут

**Comment by zvrvdmtr** [comment]
Привет, @midaef!
А какой лэйаут считается нормальным? Я смотрел несколько вариантов и, как понял, ни один из них не является обязательным.

**Comment by midaef** [comment]
@zvrvdmtr , есть определенные "бест практис" , которые используют во многих компаниях, а так вы правы нет, какого-то конкретного проджект лайаута, я уверен в большинстве случаев, если вы будете переходить из одной компании в другую, то не встретите одинаковый проджект лайаута. Если говорить про ваш проект, то я бы 1) вынес всё из pkg. 2) и переместил бы в папку app или internal

**Comment by zvrvdmtr** [comment]
@midaef , так и сделаю. Спасибо!

**Comment by midaef** [comment]
@zvrvdmtr , вот ещё можешь https://github.com/midaef/emmet-server/tree/main посмотреть мой проджект лайаут, но тут я грпс использую, мб пригодится)
